//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeaguePredictor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class players_selections
    {
        public int id { get; set; }
        public int player_id { get; set; }
        public int team_id { get; set; }
        public int position { get; set; }
    
        public virtual team team { get; set; }
        public virtual player player { get; set; }
    }
}
